# Generated by Django 4.2.2 on 2023-06-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0002_backup_restore_delete_databasebackup"),
    ]

    operations = [
        migrations.AddField(
            model_name="restore",
            name="file",
            field=models.FileField(default=0, upload_to="backups/"),
            preserve_default=False,
        ),
    ]
